// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fPyKZ2ofZPyZfzjJSSFXyvLm6w6k42o',
    appId: '1:1093587440157:web:696c668a4c6bfb056e2cf4',
    messagingSenderId: '1093587440157',
    projectId: 'tmassist-9eeec',
    authDomain: 'tmassist-9eeec.firebaseapp.com',
    storageBucket: 'tmassist-9eeec.firebasestorage.app',
    measurementId: 'G-HLCNMEW9ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTTWCLbBGAFU5svta-SIF8S19_vf-0qcA',
    appId: '1:1093587440157:android:ebf4c3544e9698e26e2cf4',
    messagingSenderId: '1093587440157',
    projectId: 'tmassist-9eeec',
    storageBucket: 'tmassist-9eeec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRiDYvXMcE3id2nKZoO9-zbLDeRp4iIw',
    appId: '1:1093587440157:ios:95a96adf66408fe86e2cf4',
    messagingSenderId: '1093587440157',
    projectId: 'tmassist-9eeec',
    storageBucket: 'tmassist-9eeec.firebasestorage.app',
    iosBundleId: 'com.example.tmassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwRiDYvXMcE3id2nKZoO9-zbLDeRp4iIw',
    appId: '1:1093587440157:ios:95a96adf66408fe86e2cf4',
    messagingSenderId: '1093587440157',
    projectId: 'tmassist-9eeec',
    storageBucket: 'tmassist-9eeec.firebasestorage.app',
    iosBundleId: 'com.example.tmassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fPyKZ2ofZPyZfzjJSSFXyvLm6w6k42o',
    appId: '1:1093587440157:web:a90ec181203b89fb6e2cf4',
    messagingSenderId: '1093587440157',
    projectId: 'tmassist-9eeec',
    authDomain: 'tmassist-9eeec.firebaseapp.com',
    storageBucket: 'tmassist-9eeec.firebasestorage.app',
    measurementId: 'G-ZQRF8QTYLG',
  );
}
